// Generated by CoffeeScript 1.6.3
(function() {
  var Chest;

  module.exports = function(game, opts) {
    return new Chest(game, opts);
  };

  module.exports.pluginInfo = {
    loadAfter: ['voxel-blockdata']
  };

  Chest = (function() {
    function Chest(game, opts) {
      this.game = game;
    }

    return Chest;

  })();

}).call(this);
